spring:
  application:
    name: ai-agent
server:
   port: 8123
   servlet:
     context-path: /api


# springdoc-openapi api??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.aiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn